---
- name: Deploy Docker Compose application
  hosts: webservers
  become: false
  vars:
    compose_file_path: /home/ec2-user/docker-compose.yml
  tasks:
    - name: stop all containers
      command: docker-compose -f "{{ compose_file_path }}" down 
      args:
        chdir: /home/ec2-user
      ignore_errors: true

    - name: copy docker-compose.yml
      copy:
        src: ../docker-compose.yml
        dest: "{{ compose_file_path }}"
        owner: ec2-user
        group: ec2-user
        mode: '0644'
        
    - name: Pull the latest images and run the containers
      command: docker-compose -f "{{ compose_file_path }}" up -d
      args:
        chdir: /home/ec2-user
