name: Spring_APP CI/CD
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  CI-CD:
################# CI Part #################
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

#Docker Build and Push
    - name: Docker Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          mohassan844/spring_app:latest
          mohassan844/spring_app:${{ github.run_number }}
        file: Dockerfile