name: Spring_APP CI
on:
  push:
    branches:
      - main
  workflow_dispatch:
jobs:
  CI-CD:
################# CI Part #################
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

#Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

#Docker Build and Push
    - name: Docker Build and Push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: |
          mohassan844/spring-app:latest
          mohassan844/spring-app:${{ github.run_number }}
        file: Dockerfile